export const ACTIVITY_CREATION_DATA = {
    'crew': {
        headerImage: 'crew.png',
        subTitle: "Créer ou rejoins un crew pour accéder à l'illégal",
        activityLabel: "Hiérarchie",
        activityList: [
            { name: "Indépendant", diminutif : "normal" },
            { name: "Gang de rue", diminutif : "gang" },
            { name: "Club de motards", diminutif : "mc" },
            { name: "Organisation criminelle", diminutif : "orga" },
            { name: "Mafia", diminutif : "mafia" },
        ],
        places: [
            { name: "Blaine County" },
            { name: "Los Santos" },
            { name: "Cayo Perico" },
        ],
        colorList: [
            "#A439A2",
            "#198D31",
            "#10561F",
            "#186E94",
            "#091B51",
            "#722E21",
            "#452019",
            "#DF6F21",
            "#44C9E5",
            "#FFFFFF",
            "#A9D4AE",
            "#ECCA32",
            "#AA1E1E",
            "#151515",
            "#149690",
            "#BA7F22",
            "#6399E0",
            "#B34141",
            "#12583A",
            "#717171",
            "#C5C5C5",
            "#32A933",
            "#A9C5A9",
            "#C22525",
            "#3DA0D0",
            "#9A9A9A",
            "#ECBAE8",
            "#000000",
            "#3198AE",
            "#10407A",
            "#EBBB52",
            "#D7D7D7",
            "#FFFFFF",
        ],
        menuColor: 'rgba(209,156,5,0.3)'
    },
    'company': {
        headerImage: 'company.png',
        subTitle: "Créer ou rejoins une entreprise",
        activityLabel: "Activité",
        activityList: [
            { name: "Bar", diminutif : "bar" },
            { name: "Restaurant", diminutif : "resto" },
            { name: "Garage", diminutif : "garage" },
            { name: "Club de nuit", diminutif : "club" },
            { name: "Épicerie", diminutif : "epicerie" },
        ],
        places: [
            { name: "Blaine County" },
            { name: "Los Santos" },
            { name: "Cayo Perico" },
        ],
        colorList: [
            "#198D31",
            "#10561F",
            "#186E94",
            "#091B51",
            "#722E21",
            "#452019",
            "#DF6F21",
            "#44C9E5",
            "#FFFFFF",
            "#A9D4AE",
            "#ECCA32",
            "#AA1E1E",
            "#151515",
            "#149690",
            "#BA7F22",
            "#6399E0",
            "#B34141",
            "#12583A",
            "#717171",
            "#C5C5C5",
            "#32A933",
            "#A9C5A9",
            "#C22525",
            "#3DA0D0",
            "#9A9A9A",
            "#ECBAE8",
            "#000000",
            "#3198AE",
            "#10407A",
            "#EBBB52",
            "#D7D7D7",
            "#FFFFFF",
        ],
        menuColor: 'linear-gradient(to top, rgba(224, 31, 31, .4), rgba(255, 0, 0, 0.2))'
    },
    'faction': {
        headerImage: 'company.png',
        subTitle: "Créer ou rejoins une Faction",
        activityLabel: "Faction",
        activityList: [
            { name: "Police", diminutif : "police" },
            { name: "Medecin", diminutif : "medecin" },
            { name: "Pompier", diminutif : "pompier" },
            { name: "Fédéral", diminutif : "federal" },
            { name: "Militaire", diminutif : "militaire" },
        ],
        places: [
            { name: "Blaine County" },
            { name: "Los Santos" },
            { name: "Cayo Perico" },
        ],
        colorList: [
            "#198D31",
            "#10561F",
            "#186E94",
            "#091B51",
            "#722E21",
            "#452019",
            "#DF6F21",
            "#44C9E5",
            "#FFFFFF",
            "#A9D4AE",
            "#ECCA32",
            "#AA1E1E",
            "#151515",
            "#149690",
            "#BA7F22",
            "#6399E0",
            "#B34141",
            "#12583A",
            "#717171",
            "#C5C5C5",
            "#32A933",
            "#A9C5A9",
            "#C22525",
            "#3DA0D0",
            "#9A9A9A",
            "#ECBAE8",
            "#000000",
            "#3198AE",
            "#10407A",
            "#EBBB52",
            "#D7D7D7",
            "#FFFFFF",
        ],
        menuColor: 'linear-gradient(to top, rgba(94, 108, 182, 0.5) 0%, rgba(94, 108, 182, 0.31) 33%, rgba(94, 108, 182, 0.31) 100%)'
    }
}