export const images = [
    { url: "https://docs.fivem.net/blips/radar_level.png", rename: 1 },
    { url: "https://docs.fivem.net/blips/radar_lower.gif", rename: 2 },
    { url: "https://docs.fivem.net/blips/radar_police_ped.gif", rename: 3 },
    { url: "https://docs.fivem.net/blips/radar_wanted_radius.png", rename: 4 },
    { url: "https://docs.fivem.net/blips/radar_area_blip.png", rename: 5 },
    { url: "https://docs.fivem.net/blips/radar_centre.png", rename: 6 },
    { url: "https://docs.fivem.net/blips/radar_north.png", rename: 7 },
    { url: "https://docs.fivem.net/blips/radar_waypoint.png", rename: 8 },
    { url: "https://docs.fivem.net/blips/radar_radius_blip.png", rename: 9 },
    { url: "https://docs.fivem.net/blips/radar_radius_outline_blip.png", rename: 10 },
    { url: "https://docs.fivem.net/blips/radar_weapon_higher.gif", rename: 11 },
    { url: "https://docs.fivem.net/blips/radar_weapon_lower.gif", rename: 12 },
    { url: "https://docs.fivem.net/blips/radar_higher_ai.gif", rename: 13 },
    { url: "https://docs.fivem.net/blips/radar_lower_ai.gif", rename: 14 },
    { url: "https://docs.fivem.net/blips/radar_police_heli_spin.png", rename: 15 },
    { url: "https://docs.fivem.net/blips/radar_police_plane_move.png", rename: 16 },
    { url: "https://docs.fivem.net/blips/radar_mp_crew.png", rename: 27 },
    { url: "https://docs.fivem.net/blips/radar_mp_friendlies.png", rename: 28 },
    { url: "https://docs.fivem.net/blips/radar_cable_car.png", rename: 36 },
    { url: "https://docs.fivem.net/blips/radar_activities.png", rename: 37 },
    { url: "https://docs.fivem.net/blips/radar_raceflag.png", rename: 38 },
    { url: "https://docs.fivem.net/blips/radar_safehouse.png", rename: 40 },
    { url: "https://docs.fivem.net/blips/radar_police.gif", rename: 41 },
    { url: "https://docs.fivem.net/blips/radar_police_chase.gif", rename: 42 },
    { url: "https://docs.fivem.net/blips/radar_police_heli.png", rename: 43 },
    { url: "https://docs.fivem.net/blips/radar_bomb_a.png", rename: 44 },
    { url: "https://docs.fivem.net/blips/radar_snitch.png", rename: 47 },
    { url: "https://docs.fivem.net/blips/radar_planning_locations.png", rename: 48 },
    { url: "https://docs.fivem.net/blips/radar_crim_carsteal.png", rename: 50 },
    { url: "https://docs.fivem.net/blips/radar_crim_drugs.png", rename: 51 },
    { url: "https://docs.fivem.net/blips/radar_crim_holdups.png", rename: 52 },
    { url: "https://docs.fivem.net/blips/radar_crim_player.png", rename: 54 },
    { url: "https://docs.fivem.net/blips/radar_cop_patrol.png", rename: 56 },
    { url: "https://docs.fivem.net/blips/radar_cop_player.png", rename: 57 },
    { url: "https://docs.fivem.net/blips/radar_crim_wanted.png", rename: 58 },
    { url: "https://docs.fivem.net/blips/radar_heist.png", rename: 59 },
    { url: "https://docs.fivem.net/blips/radar_police_station.png", rename: 60 },
    { url: "https://docs.fivem.net/blips/radar_hospital.png", rename: 61 },
    { url: "https://docs.fivem.net/blips/radar_assassins_mark.png", rename: 62 },
    { url: "https://docs.fivem.net/blips/radar_elevator.png", rename: 63 },
    { url: "https://docs.fivem.net/blips/radar_helicopter.png", rename: 64 },
    { url: "https://docs.fivem.net/blips/radar_random_character.png", rename: 66 },
    { url: "https://docs.fivem.net/blips/radar_security_van.png", rename: 67 },
    { url: "https://docs.fivem.net/blips/radar_tow_truck.png", rename: 68 },
    { url: "https://docs.fivem.net/blips/radar_illegal_parking.png", rename: 70 },
    { url: "https://docs.fivem.net/blips/radar_barber.png", rename: 71 },
    { url: "https://docs.fivem.net/blips/radar_car_mod_shop.png", rename: 72 },
    { url: "https://docs.fivem.net/blips/radar_clothes_store.png", rename: 73 },
    { url: "https://docs.fivem.net/blips/radar_tattoo.png", rename: 75 },
    { url: "https://docs.fivem.net/blips/radar_armenian_family.png", rename: 76 },
    { url: "https://docs.fivem.net/blips/radar_lester_family.png", rename: 77 },
    { url: "https://docs.fivem.net/blips/radar_michael_family.png", rename: 78 },
    { url: "https://docs.fivem.net/blips/radar_trevor_family.png", rename: 79 },
    { url: "https://docs.fivem.net/blips/radar_jewelry_heist.png", rename: 80 },
    { url: "https://docs.fivem.net/blips/radar_drag_race_finish.png", rename: 82 },
    { url: "https://docs.fivem.net/blips/radar_rampage.png", rename: 84 },
    { url: "https://docs.fivem.net/blips/radar_vinewood_tours.png", rename: 85 },
    { url: "https://docs.fivem.net/blips/radar_lamar_family.png", rename: 86 },
    { url: "https://docs.fivem.net/blips/radar_franklin_family.png", rename: 88 },
    { url: "https://docs.fivem.net/blips/radar_chinese_strand.png", rename: 89 },
    { url: "https://docs.fivem.net/blips/radar_flight_school.png", rename: 90 },
    { url: "https://docs.fivem.net/blips/radar_eye_sky.png", rename: 91 },
    { url: "https://docs.fivem.net/blips/radar_air_hockey.png", rename: 92 },
    { url: "https://docs.fivem.net/blips/radar_bar.png", rename: 93 },
    { url: "https://docs.fivem.net/blips/radar_base_jump.png", rename: 94 },
    { url: "https://docs.fivem.net/blips/radar_basketball.png", rename: 95 },
    { url: "https://docs.fivem.net/blips/radar_biolab_heist.png", rename: 96 },
    { url: "https://docs.fivem.net/blips/radar_cabaret_club.png", rename: 99 },
    { url: "https://docs.fivem.net/blips/radar_car_wash.png", rename: 100 },
    { url: "https://docs.fivem.net/blips/radar_comedy_club.png", rename: 102 },
    { url: "https://docs.fivem.net/blips/radar_darts.png", rename: 103 },
    { url: "https://docs.fivem.net/blips/radar_docks_heist.png", rename: 104 },
    { url: "https://docs.fivem.net/blips/radar_fbi_heist.png", rename: 105 },
    { url: "https://docs.fivem.net/blips/radar_fbi_officers_strand.png", rename: 106 },
    { url: "https://docs.fivem.net/blips/radar_finale_bank_heist.png", rename: 107 },
    { url: "https://docs.fivem.net/blips/radar_financier_strand.png", rename: 108 },
    { url: "https://docs.fivem.net/blips/radar_golf.png", rename: 109 },
    { url: "https://docs.fivem.net/blips/radar_gun_shop.png", rename: 110 },
    { url: "https://docs.fivem.net/blips/radar_internet_cafe.png", rename: 111 },
    { url: "https://docs.fivem.net/blips/radar_michael_family_exile.png", rename: 112 },
    { url: "https://docs.fivem.net/blips/radar_nice_house_heist.png", rename: 113 },
    { url: "https://docs.fivem.net/blips/radar_random_female.png", rename: 114 },
    { url: "https://docs.fivem.net/blips/radar_random_male.png", rename: 115 },
    { url: "https://docs.fivem.net/blips/radar_rural_bank_heist.png", rename: 118 },
    { url: "https://docs.fivem.net/blips/radar_shooting_range.png", rename: 119 },
    { url: "https://docs.fivem.net/blips/radar_solomon_strand.png", rename: 120 },
    { url: "https://docs.fivem.net/blips/radar_strip_club.png", rename: 121 },
    { url: "https://docs.fivem.net/blips/radar_tennis.png", rename: 122 },
    { url: "https://docs.fivem.net/blips/radar_trevor_family_exile.png", rename: 123 },
    { url: "https://docs.fivem.net/blips/radar_michael_trevor_family.png", rename: 124 },
    { url: "https://docs.fivem.net/blips/radar_triathlon.png", rename: 126 },
    { url: "https://docs.fivem.net/blips/radar_off_road_racing.png", rename: 127 },
    { url: "https://docs.fivem.net/blips/radar_gang_cops.png", rename: 128 },
    { url: "https://docs.fivem.net/blips/radar_gang_mexicans.png", rename: 129 },
    { url: "https://docs.fivem.net/blips/radar_gang_bikers.png", rename: 130 },
    { url: "https://docs.fivem.net/blips/radar_gang_professionals.png", rename: 132 },
    { url: "https://docs.fivem.net/blips/radar_snitch_red.png", rename: 133 },
    { url: "https://docs.fivem.net/blips/radar_crim_cuff_keys.png", rename: 134 },
    { url: "https://docs.fivem.net/blips/radar_cinema.png", rename: 135 },
    { url: "https://docs.fivem.net/blips/radar_music_venue.png", rename: 136 },
    { url: "https://docs.fivem.net/blips/radar_police_station_blue.png", rename: 137 },
    { url: "https://docs.fivem.net/blips/radar_airport.png", rename: 138 },
    { url: "https://docs.fivem.net/blips/radar_crim_saved_vehicle.png", rename: 139 },
    { url: "https://docs.fivem.net/blips/radar_weed_stash.png", rename: 140 },
    { url: "https://docs.fivem.net/blips/radar_hunting.png", rename: 141 },
    { url: "https://docs.fivem.net/blips/radar_pool.png", rename: 142 },
    { url: "https://docs.fivem.net/blips/radar_objective_blue.png", rename: 143 },
    { url: "https://docs.fivem.net/blips/radar_objective_green.png", rename: 144 },
    { url: "https://docs.fivem.net/blips/radar_objective_red.png", rename: 145 },
    { url: "https://docs.fivem.net/blips/radar_objective_yellow.png", rename: 146 },
    { url: "https://docs.fivem.net/blips/radar_arms_dealing.png", rename: 147 },
    { url: "https://docs.fivem.net/blips/radar_mp_friend.png", rename: 148 },
    { url: "https://docs.fivem.net/blips/radar_celebrity_theft.png", rename: 149 },
    { url: "https://docs.fivem.net/blips/radar_weapon_assault_rifle.png", rename: 150 },
    { url: "https://docs.fivem.net/blips/radar_weapon_bat.png", rename: 151 },
    { url: "https://docs.fivem.net/blips/radar_weapon_grenade.png", rename: 152 },
    { url: "https://docs.fivem.net/blips/radar_weapon_health.png", rename: 153 },
    { url: "https://docs.fivem.net/blips/radar_weapon_knife.png", rename: 154 },
    { url: "https://docs.fivem.net/blips/radar_weapon_molotov.png", rename: 155 },
    { url: "https://docs.fivem.net/blips/radar_weapon_pistol.png", rename: 156 },
    { url: "https://docs.fivem.net/blips/radar_weapon_rocket.png", rename: 157 },
    { url: "https://docs.fivem.net/blips/radar_weapon_shotgun.png", rename: 158 },
    { url: "https://docs.fivem.net/blips/radar_weapon_smg.png", rename: 159 },
    { url: "https://docs.fivem.net/blips/radar_weapon_sniper.png", rename: 160 },
    { url: "https://docs.fivem.net/blips/radar_mp_noise.gif", rename: 161 },
    { url: "https://docs.fivem.net/blips/radar_poi.png", rename: 162 },
    { url: "https://docs.fivem.net/blips/radar_passive.png", rename: 163 },
    { url: "https://docs.fivem.net/blips/radar_usingmenu.png", rename: 164 },
    { url: "https://docs.fivem.net/blips/radar_gang_cops_partner.png", rename: 171 },
    { url: "https://docs.fivem.net/blips/radar_weapon_minigun.png", rename: 173 },
    { url: "https://docs.fivem.net/blips/radar_weapon_armour.png", rename: 175 },
    { url: "https://docs.fivem.net/blips/radar_property_takeover.png", rename: 176 },
    { url: "https://docs.fivem.net/blips/radar_gang_mexicans_highlight.png", rename: 177 },
    { url: "https://docs.fivem.net/blips/radar_gang_bikers_highlight.png", rename: 178 },
    { url: "https://docs.fivem.net/blips/radar_triathlon_cycling.png", rename: 179 },
    { url: "https://docs.fivem.net/blips/radar_triathlon_swimming.png", rename: 180 },
    { url: "https://docs.fivem.net/blips/radar_property_takeover_bikers.png", rename: 181 },
    { url: "https://docs.fivem.net/blips/radar_property_takeover_cops.png", rename: 182 },
    { url: "https://docs.fivem.net/blips/radar_property_takeover_vagos.png", rename: 183 },
    { url: "https://docs.fivem.net/blips/radar_camera.png", rename: 184 },
    { url: "https://docs.fivem.net/blips/radar_centre_red.png", rename: 185 },
    { url: "https://docs.fivem.net/blips/radar_handcuff_keys_bikers.png", rename: 186 },
    { url: "https://docs.fivem.net/blips/radar_handcuff_keys_vagos.png", rename: 187 },
    { url: "https://docs.fivem.net/blips/radar_handcuffs_closed_bikers.png", rename: 188 },
    { url: "https://docs.fivem.net/blips/radar_handcuffs_closed_vagos.png", rename: 189 },
    { url: "https://docs.fivem.net/blips/radar_camera_badger.png", rename: 192 },
    { url: "https://docs.fivem.net/blips/radar_camera_facade.png", rename: 193 },
    { url: "https://docs.fivem.net/blips/radar_camera_ifruit.png", rename: 194 },
    { url: "https://docs.fivem.net/blips/radar_yoga.png", rename: 197 },
    { url: "https://docs.fivem.net/blips/radar_taxi.png", rename: 198 },
    { url: "https://docs.fivem.net/blips/radar_shrink.png", rename: 205 },
    { url: "https://docs.fivem.net/blips/radar_epsilon.png", rename: 206 },
    { url: "https://docs.fivem.net/blips/radar_financier_strand_grey.png", rename: 207 },
    { url: "https://docs.fivem.net/blips/radar_trevor_family_grey.png", rename: 208 },
    { url: "https://docs.fivem.net/blips/radar_trevor_family_red.png", rename: 209 },
    { url: "https://docs.fivem.net/blips/radar_franklin_family_grey.png", rename: 210 },
    { url: "https://docs.fivem.net/blips/radar_franklin_family_blue.png", rename: 211 },
    { url: "https://docs.fivem.net/blips/radar_franklin_a.png", rename: 212 },
    { url: "https://docs.fivem.net/blips/radar_franklin_b.png", rename: 213 },
    { url: "https://docs.fivem.net/blips/radar_franklin_c.png", rename: 214 },
    { url: "https://docs.fivem.net/blips/radar_gang_vehicle.png", rename: 225 },
    { url: "https://docs.fivem.net/blips/radar_gang_vehicle_bikers.png", rename: 226 },
    { url: "https://docs.fivem.net/blips/radar_gang_vehicle_cops.png", rename: 227 },
    { url: "https://docs.fivem.net/blips/radar_gang_vehicle_vagos.png", rename: 228 },
    { url: "https://docs.fivem.net/blips/radar_guncar.png", rename: 229 },
    { url: "https://docs.fivem.net/blips/radar_driving_bikers.png", rename: 230 },
    { url: "https://docs.fivem.net/blips/radar_driving_cops.png", rename: 231 },
    { url: "https://docs.fivem.net/blips/radar_driving_vagos.png", rename: 232 },
    { url: "https://docs.fivem.net/blips/radar_gang_cops_highlight.png", rename: 233 },
    { url: "https://docs.fivem.net/blips/radar_shield_bikers.png", rename: 234 },
    { url: "https://docs.fivem.net/blips/radar_shield_cops.png", rename: 235 },
    { url: "https://docs.fivem.net/blips/radar_shield_vagos.png", rename: 236 },
    { url: "https://docs.fivem.net/blips/radar_custody_bikers.png", rename: 237 },
    { url: "https://docs.fivem.net/blips/radar_custody_vagos.png", rename: 238 },
    { url: "https://docs.fivem.net/blips/radar_arms_dealing_air.png", rename: 251 },
    { url: "https://docs.fivem.net/blips/radar_playerstate_arrested.png", rename: 252 },
    { url: "https://docs.fivem.net/blips/radar_playerstate_custody.png", rename: 253 },
    { url: "https://docs.fivem.net/blips/radar_playerstate_driving.png", rename: 254 },
    { url: "https://docs.fivem.net/blips/radar_playerstate_keyholder.png", rename: 255 },
    { url: "https://docs.fivem.net/blips/radar_playerstate_partner.png", rename: 256 },
    { url: "https://docs.fivem.net/blips/radar_ztype.png", rename: 262 },
    { url: "https://docs.fivem.net/blips/radar_stinger.png", rename: 263 },
    { url: "https://docs.fivem.net/blips/radar_packer.png", rename: 264 },
    { url: "https://docs.fivem.net/blips/radar_monroe.png", rename: 265 },
    { url: "https://docs.fivem.net/blips/radar_fairground.png", rename: 266 },
    { url: "https://docs.fivem.net/blips/radar_property.png", rename: 267 },
    { url: "https://docs.fivem.net/blips/radar_gang_highlight.png", rename: 268 },
    { url: "https://docs.fivem.net/blips/radar_altruist.png", rename: 269 },
    { url: "https://docs.fivem.net/blips/radar_ai.png", rename: 270 },
    { url: "https://docs.fivem.net/blips/radar_on_mission.png", rename: 271 },
    { url: "https://docs.fivem.net/blips/radar_cash_pickup.png", rename: 272 },
    { url: "https://docs.fivem.net/blips/radar_chop.png", rename: 273 },
    { url: "https://docs.fivem.net/blips/radar_dead.png", rename: 274 },
    { url: "https://docs.fivem.net/blips/radar_territory_locked.png", rename: 275 },
    { url: "https://docs.fivem.net/blips/radar_cash_lost.png", rename: 276 },
    { url: "https://docs.fivem.net/blips/radar_cash_vagos.png", rename: 277 },
    { url: "https://docs.fivem.net/blips/radar_cash_cops.png", rename: 278 },
    { url: "https://docs.fivem.net/blips/radar_hooker.png", rename: 279 },
    { url: "https://docs.fivem.net/blips/radar_friend.png", rename: 280 },
    { url: "https://docs.fivem.net/blips/radar_mission_2to4.png", rename: 281 },
    { url: "https://docs.fivem.net/blips/radar_mission_2to8.png", rename: 282 },
    { url: "https://docs.fivem.net/blips/radar_mission_2to12.png", rename: 283 },
    { url: "https://docs.fivem.net/blips/radar_mission_2to16.png", rename: 284 },
    { url: "https://docs.fivem.net/blips/radar_custody_dropoff.png", rename: 285 },
    { url: "https://docs.fivem.net/blips/radar_onmission_cops.png", rename: 286 },
    { url: "https://docs.fivem.net/blips/radar_onmission_lost.png", rename: 287 },
    { url: "https://docs.fivem.net/blips/radar_onmission_vagos.png", rename: 288 },
    { url: "https://docs.fivem.net/blips/radar_crim_carsteal_cops.png", rename: 289 },
    { url: "https://docs.fivem.net/blips/radar_crim_carsteal_bikers.png", rename: 290 },
    { url: "https://docs.fivem.net/blips/radar_crim_carsteal_vagos.png", rename: 291 },
    { url: "https://docs.fivem.net/blips/radar_band_strand.png", rename: 292 },
    { url: "https://docs.fivem.net/blips/radar_simeon_family.png", rename: 293 },
    { url: "https://docs.fivem.net/blips/radar_mission_1.png", rename: 294 },
    { url: "https://docs.fivem.net/blips/radar_mission_2.png", rename: 295 },
    { url: "https://docs.fivem.net/blips/radar_friend_darts.png", rename: 296 },
    { url: "https://docs.fivem.net/blips/radar_friend_comedyclub.png", rename: 297 },
    { url: "https://docs.fivem.net/blips/radar_friend_cinema.png", rename: 298 },
    { url: "https://docs.fivem.net/blips/radar_friend_tennis.png", rename: 299 },
    { url: "https://docs.fivem.net/blips/radar_friend_stripclub.png", rename: 300 },
    { url: "https://docs.fivem.net/blips/radar_friend_livemusic.png", rename: 301 },
    { url: "https://docs.fivem.net/blips/radar_friend_golf.png", rename: 302 },
    { url: "https://docs.fivem.net/blips/radar_bounty_hit.png", rename: 303 },
    { url: "https://docs.fivem.net/blips/radar_ugc_mission.png", rename: 304 },
    { url: "https://docs.fivem.net/blips/radar_horde.png", rename: 305 },
    { url: "https://docs.fivem.net/blips/radar_cratedrop.png", rename: 306 },
    { url: "https://docs.fivem.net/blips/radar_plane_drop.png", rename: 307 },
    { url: "https://docs.fivem.net/blips/radar_sub.png", rename: 308 },
    { url: "https://docs.fivem.net/blips/radar_race.png", rename: 309 },
    { url: "https://docs.fivem.net/blips/radar_deathmatch.png", rename: 310 },
    { url: "https://docs.fivem.net/blips/radar_arm_wrestling.png", rename: 311 },
    { url: "https://docs.fivem.net/blips/radar_mission_1to2.png", rename: 312 },
    { url: "https://docs.fivem.net/blips/radar_shootingrange_gunshop.png", rename: 313 },
    { url: "https://docs.fivem.net/blips/radar_race_air.png", rename: 314 },
    { url: "https://docs.fivem.net/blips/radar_race_land.png", rename: 315 },
    { url: "https://docs.fivem.net/blips/radar_race_sea.png", rename: 316 },
    { url: "https://docs.fivem.net/blips/radar_tow.png", rename: 317 },
    { url: "https://docs.fivem.net/blips/radar_garbage.png", rename: 318 },
    { url: "https://docs.fivem.net/blips/radar_drill.png", rename: 319 },
    { url: "https://docs.fivem.net/blips/radar_spikes.png", rename: 320 },
    { url: "https://docs.fivem.net/blips/radar_firetruck.png", rename: 321 },
    { url: "https://docs.fivem.net/blips/radar_minigun2.png", rename: 322 },
    { url: "https://docs.fivem.net/blips/radar_bugstar.png", rename: 323 },
    { url: "https://docs.fivem.net/blips/radar_submarine.png", rename: 324 },
    { url: "https://docs.fivem.net/blips/radar_chinook.png", rename: 325 },
    { url: "https://docs.fivem.net/blips/radar_getaway_car.png", rename: 326 },
    { url: "https://docs.fivem.net/blips/radar_mission_bikers_1.png", rename: 327 },
    { url: "https://docs.fivem.net/blips/radar_mission_bikers_1to2.png", rename: 328 },
    { url: "https://docs.fivem.net/blips/radar_mission_bikers_2.png", rename: 329 },
    { url: "https://docs.fivem.net/blips/radar_gang_bike.png", rename: 348 },
    { url: "https://docs.fivem.net/blips/radar_gas_grenade.png", rename: 349 },
    { url: "https://docs.fivem.net/blips/radar_property_for_sale.png", rename: 350 },
    { url: "https://docs.fivem.net/blips/radar_gang_attack_package.png", rename: 351 },
    { url: "https://docs.fivem.net/blips/radar_martin_madrazzo.png", rename: 352 },
    { url: "https://docs.fivem.net/blips/radar_enemy_heli_spin.gif", rename: 353 },
    { url: "https://docs.fivem.net/blips/radar_boost.png", rename: 354 },
    { url: "https://docs.fivem.net/blips/radar_devin.png", rename: 355 },
    { url: "https://docs.fivem.net/blips/radar_dock.png", rename: 356 },
    { url: "https://docs.fivem.net/blips/radar_garage.png", rename: 357 },
    { url: "https://docs.fivem.net/blips/radar_golf_flag.png", rename: 358 },
    { url: "https://docs.fivem.net/blips/radar_hangar.png", rename: 359 },
    { url: "https://docs.fivem.net/blips/radar_helipad.png", rename: 360 },
    { url: "https://docs.fivem.net/blips/radar_jerry_can.png", rename: 361 },
    { url: "https://docs.fivem.net/blips/radar_mask.png", rename: 362 },
    { url: "https://docs.fivem.net/blips/radar_heist_prep.png", rename: 363 },
    { url: "https://docs.fivem.net/blips/radar_incapacitated.png", rename: 364 },
    { url: "https://docs.fivem.net/blips/radar_spawn_point_pickup.png", rename: 365 },
    { url: "https://docs.fivem.net/blips/radar_boilersuit.png", rename: 366 },
    { url: "https://docs.fivem.net/blips/radar_completed.png", rename: 367 },
    { url: "https://docs.fivem.net/blips/radar_rockets.png", rename: 368 },
    { url: "https://docs.fivem.net/blips/radar_garage_for_sale.png", rename: 369 },
    { url: "https://docs.fivem.net/blips/radar_helipad_for_sale.png", rename: 370 },
    { url: "https://docs.fivem.net/blips/radar_dock_for_sale.png", rename: 371 },
    { url: "https://docs.fivem.net/blips/radar_hangar_for_sale.png", rename: 372 },
    { url: "https://docs.fivem.net/blips/radar_placeholder_6.png", rename: 373 },
    { url: "https://docs.fivem.net/blips/radar_business.png", rename: 374 },
    { url: "https://docs.fivem.net/blips/radar_business_for_sale.png", rename: 375 },
    { url: "https://docs.fivem.net/blips/radar_race_bike.png", rename: 376 },
    { url: "https://docs.fivem.net/blips/radar_parachute.png", rename: 377 },
    { url: "https://docs.fivem.net/blips/radar_team_deathmatch.png", rename: 378 },
    { url: "https://docs.fivem.net/blips/radar_race_foot.png", rename: 379 },
    { url: "https://docs.fivem.net/blips/radar_vehicle_deathmatch.png", rename: 380 },
    { url: "https://docs.fivem.net/blips/radar_barry.png", rename: 381 },
    { url: "https://docs.fivem.net/blips/radar_dom.png", rename: 382 },
    { url: "https://docs.fivem.net/blips/radar_maryann.png", rename: 383 },
    { url: "https://docs.fivem.net/blips/radar_cletus.png", rename: 384 },
    { url: "https://docs.fivem.net/blips/radar_josh.png", rename: 385 },
    { url: "https://docs.fivem.net/blips/radar_minute.png", rename: 386 },
    { url: "https://docs.fivem.net/blips/radar_omega.png", rename: 387 },
    { url: "https://docs.fivem.net/blips/radar_tonya.png", rename: 388 },
    { url: "https://docs.fivem.net/blips/radar_paparazzo.png", rename: 389 },
    { url: "https://docs.fivem.net/blips/radar_aim.png", rename: 390 },
    { url: "https://docs.fivem.net/blips/radar_cratedrop_background.png", rename: 391 },
    { url: "https://docs.fivem.net/blips/radar_green_and_net_player1.png", rename: 392 },
    { url: "https://docs.fivem.net/blips/radar_green_and_net_player2.png", rename: 393 },
    { url: "https://docs.fivem.net/blips/radar_green_and_net_player3.png", rename: 394 },
    { url: "https://docs.fivem.net/blips/radar_green_and_friendly.png", rename: 395 },
    { url: "https://docs.fivem.net/blips/radar_net_player1_and_net_player2.png", rename: 396 },
    { url: "https://docs.fivem.net/blips/radar_net_player1_and_net_player3.png", rename: 397 },
    { url: "https://docs.fivem.net/blips/radar_creator.png", rename: 398 },
    { url: "https://docs.fivem.net/blips/radar_creator_direction.png", rename: 399 },
    { url: "https://docs.fivem.net/blips/radar_abigail.png", rename: 400 },
    { url: "https://docs.fivem.net/blips/radar_blimp.png", rename: 401 },
    { url: "https://docs.fivem.net/blips/radar_repair.png", rename: 402 },
    { url: "https://docs.fivem.net/blips/radar_testosterone.png", rename: 403 },
    { url: "https://docs.fivem.net/blips/radar_dinghy.png", rename: 404 },
    { url: "https://docs.fivem.net/blips/radar_fanatic.png", rename: 405 },
    { url: "https://docs.fivem.net/blips/radar_info_icon.png", rename: 407 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_flag.png", rename: 408 },
    { url: "https://docs.fivem.net/blips/radar_last_team_standing.png", rename: 409 },
    { url: "https://docs.fivem.net/blips/radar_boat.png", rename: 410 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_flag_base.png", rename: 411 },
    { url: "https://docs.fivem.net/blips/radar_mp_crew.png", rename: 412 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_flag_outline.png", rename: 413 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_flag_base_nobag.png", rename: 414 },
    { url: "https://docs.fivem.net/blips/radar_weapon_jerrycan.png", rename: 415 },
    { url: "https://docs.fivem.net/blips/radar_rp.png", rename: 416 },
    { url: "https://docs.fivem.net/blips/radar_level_inside.png", rename: 417 },
    { url: "https://docs.fivem.net/blips/radar_bounty_hit_inside.png", rename: 418 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_usaflag.png", rename: 419 },
    { url: "https://docs.fivem.net/blips/radar_capture_the_usaflag_outline.png", rename: 420 },
    { url: "https://docs.fivem.net/blips/radar_tank.png", rename: 421 },
    { url: "https://docs.fivem.net/blips/radar_player_heli.gif", rename: 422 },
    { url: "https://docs.fivem.net/blips/radar_player_plane.png", rename: 423 },
    { url: "https://docs.fivem.net/blips/radar_player_jet.png", rename: 424 },
    { url: "https://docs.fivem.net/blips/radar_centre_stroke.png", rename: 425 },
    { url: "https://docs.fivem.net/blips/radar_player_guncar.png", rename: 426 },
    { url: "https://docs.fivem.net/blips/radar_player_boat.png", rename: 427 },
    { url: "https://docs.fivem.net/blips/radar_mp_heist.png", rename: 428 },
    { url: "https://docs.fivem.net/blips/radar_temp_1.png", rename: 429 },
    { url: "https://docs.fivem.net/blips/radar_temp_2.png", rename: 430 },
    { url: "https://docs.fivem.net/blips/radar_temp_3.png", rename: 431 },
    { url: "https://docs.fivem.net/blips/radar_temp_4.png", rename: 432 },
    { url: "https://docs.fivem.net/blips/radar_temp_5.png", rename: 433 },
    { url: "https://docs.fivem.net/blips/radar_temp_6.png", rename: 434 },
    { url: "https://docs.fivem.net/blips/radar_race_stunt.png", rename: 435 },
    { url: "https://docs.fivem.net/blips/radar_hot_property.png", rename: 436 },
    { url: "https://docs.fivem.net/blips/radar_urbanwarfare_versus.png", rename: 437 },
    { url: "https://docs.fivem.net/blips/radar_king_of_the_castle.png", rename: 438 },
    { url: "https://docs.fivem.net/blips/radar_player_king.png", rename: 439 },
    { url: "https://docs.fivem.net/blips/radar_dead_drop.png", rename: 440 },
    { url: "https://docs.fivem.net/blips/radar_penned_in.png", rename: 441 },
    { url: "https://docs.fivem.net/blips/radar_beast.png", rename: 442 },
    { url: "https://docs.fivem.net/blips/radar_edge_pointer.png", rename: 443 },
    { url: "https://docs.fivem.net/blips/radar_edge_crosstheline.png", rename: 444 },
    { url: "https://docs.fivem.net/blips/radar_mp_lamar.png", rename: 445 },
    { url: "https://docs.fivem.net/blips/radar_bennys.png", rename: 446 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_1.png", rename: 447 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_2.png", rename: 448 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_3.png", rename: 449 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_4.png", rename: 450 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_5.png", rename: 451 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_6.png", rename: 452 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_7.png", rename: 453 },
    { url: "https://docs.fivem.net/blips/radar_corner_number_8.png", rename: 454 },
    { url: "https://docs.fivem.net/blips/radar_yacht.png", rename: 455 },
    { url: "https://docs.fivem.net/blips/radar_finders_keepers.png", rename: 456 },
    { url: "https://docs.fivem.net/blips/radar_assault_package.png", rename: 457 },
    { url: "https://docs.fivem.net/blips/radar_hunt_the_boss.png", rename: 458 },
    { url: "https://docs.fivem.net/blips/radar_sightseer.png", rename: 459 },
    { url: "https://docs.fivem.net/blips/radar_turreted_limo.png", rename: 460 },
    { url: "https://docs.fivem.net/blips/radar_belly_of_the_beast.png", rename: 461 },
    { url: "https://docs.fivem.net/blips/radar_yacht_location.png", rename: 462 },
    { url: "https://docs.fivem.net/blips/radar_pickup_beast.png", rename: 463 },
    { url: "https://docs.fivem.net/blips/radar_pickup_zoned.png", rename: 464 },
    { url: "https://docs.fivem.net/blips/radar_pickup_random.png", rename: 465 },
    { url: "https://docs.fivem.net/blips/radar_pickup_slow_time.png", rename: 466 },
    { url: "https://docs.fivem.net/blips/radar_pickup_swap.png", rename: 467 },
    { url: "https://docs.fivem.net/blips/radar_pickup_thermal.png", rename: 468 },
    { url: "https://docs.fivem.net/blips/radar_pickup_weed.png", rename: 469 },
    { url: "https://docs.fivem.net/blips/radar_weapon_railgun.png", rename: 470 },
    { url: "https://docs.fivem.net/blips/radar_seashark.png", rename: 471 },
    { url: "https://docs.fivem.net/blips/radar_pickup_hidden.png", rename: 472 },
    { url: "https://docs.fivem.net/blips/radar_warehouse.png", rename: 473 },
    { url: "https://docs.fivem.net/blips/radar_warehouse_for_sale.png", rename: 474 },
    { url: "https://docs.fivem.net/blips/radar_office.png", rename: 475 },
    { url: "https://docs.fivem.net/blips/radar_office_for_sale.png", rename: 476 },
    { url: "https://docs.fivem.net/blips/radar_truck.png", rename: 477 },
    { url: "https://docs.fivem.net/blips/radar_contraband.png", rename: 478 },
    { url: "https://docs.fivem.net/blips/radar_trailer.png", rename: 479 },
    { url: "https://docs.fivem.net/blips/radar_vip.png", rename: 480 },
    { url: "https://docs.fivem.net/blips/radar_cargobob.png", rename: 481 },
    { url: "https://docs.fivem.net/blips/radar_area_outline_blip.png", rename: 482 },
    { url: "https://docs.fivem.net/blips/radar_pickup_accelerator.png", rename: 483 },
    { url: "https://docs.fivem.net/blips/radar_pickup_ghost.png", rename: 484 },
    { url: "https://docs.fivem.net/blips/radar_pickup_detonator.png", rename: 485 },
    { url: "https://docs.fivem.net/blips/radar_pickup_bomb.png", rename: 486 },
    { url: "https://docs.fivem.net/blips/radar_pickup_armoured.png", rename: 487 },
    { url: "https://docs.fivem.net/blips/radar_stunt.png", rename: 488 },
    { url: "https://docs.fivem.net/blips/radar_weapon_lives.png", rename: 489 },
    { url: "https://docs.fivem.net/blips/radar_stunt_premium.png", rename: 490 },
    { url: "https://docs.fivem.net/blips/radar_adversary.png", rename: 491 },
    { url: "https://docs.fivem.net/blips/radar_biker_clubhouse.png", rename: 492 },
    { url: "https://docs.fivem.net/blips/radar_biker_caged_in.png", rename: 493 },
    { url: "https://docs.fivem.net/blips/radar_biker_turf_war.png", rename: 494 },
    { url: "https://docs.fivem.net/blips/radar_biker_joust.png", rename: 495 },
    { url: "https://docs.fivem.net/blips/radar_production_weed.png", rename: 496 },
    { url: "https://docs.fivem.net/blips/radar_production_crack.png", rename: 497 },
    { url: "https://docs.fivem.net/blips/radar_production_fake_id.png", rename: 498 },
    { url: "https://docs.fivem.net/blips/radar_production_meth.png", rename: 499 },
    { url: "https://docs.fivem.net/blips/radar_production_money.png", rename: 500 },
    { url: "https://docs.fivem.net/blips/radar_package.png", rename: 501 },
    { url: "https://docs.fivem.net/blips/radar_capture_1.png", rename: 502 },
    { url: "https://docs.fivem.net/blips/radar_capture_2.png", rename: 503 },
    { url: "https://docs.fivem.net/blips/radar_capture_3.png", rename: 504 },
    { url: "https://docs.fivem.net/blips/radar_capture_4.png", rename: 505 },
    { url: "https://docs.fivem.net/blips/radar_capture_5.png", rename: 506 },
    { url: "https://docs.fivem.net/blips/radar_capture_6.png", rename: 507 },
    { url: "https://docs.fivem.net/blips/radar_capture_7.png", rename: 508 },
    { url: "https://docs.fivem.net/blips/radar_capture_8.png", rename: 509 },
    { url: "https://docs.fivem.net/blips/radar_capture_9.png", rename: 510 },
    { url: "https://docs.fivem.net/blips/radar_capture_10.png", rename: 511 },
    { url: "https://docs.fivem.net/blips/radar_quad.png", rename: 512 },
    { url: "https://docs.fivem.net/blips/radar_bus.png", rename: 513 },
    { url: "https://docs.fivem.net/blips/radar_drugs_package.png", rename: 514 },
    { url: "https://docs.fivem.net/blips/radar_pickup_jump.png", rename: 515 },
    { url: "https://docs.fivem.net/blips/radar_adversary_4.png", rename: 516 },
    { url: "https://docs.fivem.net/blips/radar_adversary_8.png", rename: 517 },
    { url: "https://docs.fivem.net/blips/radar_adversary_10.png", rename: 518 },
    { url: "https://docs.fivem.net/blips/radar_adversary_12.png", rename: 519 },
    { url: "https://docs.fivem.net/blips/radar_adversary_16.png", rename: 520 },
    { url: "https://docs.fivem.net/blips/radar_laptop.png", rename: 521 },
    { url: "https://docs.fivem.net/blips/radar_pickup_deadline.png", rename: 522 },
    { url: "https://docs.fivem.net/blips/radar_sports_car.png", rename: 523 },
    { url: "https://docs.fivem.net/blips/radar_warehouse_vehicle.png", rename: 524 },
    { url: "https://docs.fivem.net/blips/radar_reg_papers.png", rename: 525 },
    { url: "https://docs.fivem.net/blips/radar_police_station_dropoff.png", rename: 526 },
    { url: "https://docs.fivem.net/blips/radar_junkyard.png", rename: 527 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_1.png", rename: 528 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_2.png", rename: 529 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_3.png", rename: 530 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_4.png", rename: 531 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_5.png", rename: 532 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_6.png", rename: 533 },
    { url: "https://docs.fivem.net/blips/radar_ex_vech_7.png", rename: 534 },
    { url: "https://docs.fivem.net/blips/radar_target_a.png", rename: 535 },
    { url: "https://docs.fivem.net/blips/radar_target_b.png", rename: 536 },
    { url: "https://docs.fivem.net/blips/radar_target_c.png", rename: 537 },
    { url: "https://docs.fivem.net/blips/radar_target_d.png", rename: 538 },
    { url: "https://docs.fivem.net/blips/radar_target_e.png", rename: 539 },
    { url: "https://docs.fivem.net/blips/radar_target_f.png", rename: 540 },
    { url: "https://docs.fivem.net/blips/radar_target_g.png", rename: 541 },
    { url: "https://docs.fivem.net/blips/radar_target_h.png", rename: 542 },
    { url: "https://docs.fivem.net/blips/radar_jugg.png", rename: 543 },
    { url: "https://docs.fivem.net/blips/radar_pickup_repair.png", rename: 544 },
    { url: "https://docs.fivem.net/blips/radar_steeringwheel.png", rename: 545 },
    { url: "https://docs.fivem.net/blips/radar_trophy.png", rename: 546 },
    { url: "https://docs.fivem.net/blips/radar_pickup_rocket_boost.png", rename: 547 },
    { url: "https://docs.fivem.net/blips/radar_pickup_homing_rocket.png", rename: 548 },
    { url: "https://docs.fivem.net/blips/radar_pickup_machinegun.png", rename: 549 },
    { url: "https://docs.fivem.net/blips/radar_pickup_parachute.png", rename: 550 },
    { url: "https://docs.fivem.net/blips/radar_pickup_time_5.png", rename: 551 },
    { url: "https://docs.fivem.net/blips/radar_pickup_time_10.png", rename: 552 },
    { url: "https://docs.fivem.net/blips/radar_pickup_time_15.png", rename: 553 },
    { url: "https://docs.fivem.net/blips/radar_pickup_time_20.png", rename: 554 },
    { url: "https://docs.fivem.net/blips/radar_pickup_time_30.png", rename: 555 },
    { url: "https://docs.fivem.net/blips/radar_supplies.png", rename: 556 },
    { url: "https://docs.fivem.net/blips/radar_property_bunker.png", rename: 557 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_1.png", rename: 558 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_2.png", rename: 559 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_3.png", rename: 560 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_4.png", rename: 561 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_5.png", rename: 562 },
    { url: "https://docs.fivem.net/blips/radar_gr_wvm_6.png", rename: 563 },
    { url: "https://docs.fivem.net/blips/radar_gr_covert_ops.png", rename: 564 },
    { url: "https://docs.fivem.net/blips/radar_adversary_bunker.png", rename: 565 },
    { url: "https://docs.fivem.net/blips/radar_gr_moc_upgrade.png", rename: 566 },
    { url: "https://docs.fivem.net/blips/radar_gr_w_upgrade.png", rename: 567 },
    { url: "https://docs.fivem.net/blips/radar_sm_cargo.png", rename: 568 },
    { url: "https://docs.fivem.net/blips/radar_sm_hangar.png", rename: 569 },
    { url: "https://docs.fivem.net/blips/radar_tf_checkpoint.png", rename: 570 },
    { url: "https://docs.fivem.net/blips/radar_race_tf.png", rename: 571 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp1.png", rename: 572 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp2.png", rename: 573 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp3.png", rename: 574 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp4.png", rename: 575 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp5.png", rename: 576 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp6.png", rename: 577 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp7.png", rename: 578 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp8.png", rename: 579 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp9.png", rename: 580 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp10.png", rename: 581 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp11.png", rename: 582 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp12.png", rename: 583 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp13.png", rename: 584 },
    { url: "https://docs.fivem.net/blips/radar_sm_wp14.png", rename: 585 },
    { url: "https://docs.fivem.net/blips/radar_nhp_bag.png", rename: 586 },
    { url: "https://docs.fivem.net/blips/radar_nhp_chest.png", rename: 587 },
    { url: "https://docs.fivem.net/blips/radar_nhp_orbit.png", rename: 588 },
    { url: "https://docs.fivem.net/blips/radar_nhp_veh1.png", rename: 589 },
    { url: "https://docs.fivem.net/blips/radar_nhp_base.png", rename: 590 },
    { url: "https://docs.fivem.net/blips/radar_nhp_overlay.png", rename: 591 },
    { url: "https://docs.fivem.net/blips/radar_nhp_turret.png", rename: 592 },
    { url: "https://docs.fivem.net/blips/radar_nhp_mg_firewall.png", rename: 593 },
    { url: "https://docs.fivem.net/blips/radar_nhp_mg_node.png", rename: 594 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp1.png", rename: 595 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp2.png", rename: 596 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp3.png", rename: 597 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp4.png", rename: 598 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp5.png", rename: 599 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp6.png", rename: 600 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp7.png", rename: 601 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp8.png", rename: 602 },
    { url: "https://docs.fivem.net/blips/radar_nhp_wp9.png", rename: 603 },
    { url: "https://docs.fivem.net/blips/radar_nhp_cctv.png", rename: 604 },
    { url: "https://docs.fivem.net/blips/radar_nhp_starterpack.png", rename: 605 },
    { url: "https://docs.fivem.net/blips/radar_nhp_turret_console.png", rename: 606 },
    { url: "https://docs.fivem.net/blips/radar_nhp_mg_mir_rotate.png", rename: 607 },
    { url: "https://docs.fivem.net/blips/radar_nhp_mg_mir_static.png", rename: 608 },
    { url: "https://docs.fivem.net/blips/radar_nhp_mg_proxy.png", rename: 609 },
    { url: "https://docs.fivem.net/blips/radar_acsr_race_target.png", rename: 610 },
    { url: "https://docs.fivem.net/blips/radar_acsr_race_hotring.png", rename: 611 },
    { url: "https://docs.fivem.net/blips/radar_acsr_wp1.png", rename: 612 },
    { url: "https://docs.fivem.net/blips/radar_acsr_wp2.png", rename: 613 },
    { url: "https://docs.fivem.net/blips/radar_bat_club_property.png", rename: 614 },
    { url: "https://docs.fivem.net/blips/radar_bat_cargo.png", rename: 615 },
    { url: "https://docs.fivem.net/blips/radar_bat_truck.png", rename: 616 },
    { url: "https://docs.fivem.net/blips/radar_bat_hack_jewel.png", rename: 617 },
    { url: "https://docs.fivem.net/blips/radar_bat_hack_gold.png", rename: 618 },
    { url: "https://docs.fivem.net/blips/radar_bat_keypad.png", rename: 619 },
    { url: "https://docs.fivem.net/blips/radar_bat_hack_target.png", rename: 620 },
    { url: "https://docs.fivem.net/blips/radar_pickup_dtb_health.png", rename: 621 },
    { url: "https://docs.fivem.net/blips/radar_pickup_dtb_blast_increase.png", rename: 622 },
    { url: "https://docs.fivem.net/blips/radar_pickup_dtb_blast_decrease.png", rename: 623 },
    { url: "https://docs.fivem.net/blips/radar_pickup_dtb_bomb_increase.png", rename: 624 },
    { url: "https://docs.fivem.net/blips/radar_pickup_dtb_bomb_decrease.png", rename: 625 },
    { url: "https://docs.fivem.net/blips/radar_bat_rival_club.png", rename: 626 },
    { url: "https://docs.fivem.net/blips/radar_bat_drone.png", rename: 627 },
    { url: "https://docs.fivem.net/blips/radar_bat_cash_reg.png", rename: 628 },
    { url: "https://docs.fivem.net/blips/radar_cctv.png", rename: 629 },
    { url: "https://docs.fivem.net/blips/radar_bat_assassinate.png", rename: 630 },
    { url: "https://docs.fivem.net/blips/radar_bat_pbus.png", rename: 631 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp1.png", rename: 632 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp2.png", rename: 633 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp3.png", rename: 634 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp4.png", rename: 635 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp5.png", rename: 636 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp6.png", rename: 637 },
    { url: "https://docs.fivem.net/blips/radar_blimp_2.png", rename: 638 },
    { url: "https://docs.fivem.net/blips/radar_oppressor_2.png", rename: 639 },
    { url: "https://docs.fivem.net/blips/radar_bat_wp7.png", rename: 640 },
    { url: "https://docs.fivem.net/blips/radar_arena_series.png", rename: 641 },
    { url: "https://docs.fivem.net/blips/radar_arena_premium.png", rename: 642 },
    { url: "https://docs.fivem.net/blips/radar_arena_workshop.png", rename: 643 },
    { url: "https://docs.fivem.net/blips/radar_race_wars.png", rename: 644 },
    { url: "https://docs.fivem.net/blips/radar_arena_turret.png", rename: 645 },
    { url: "https://docs.fivem.net/blips/radar_arena_rc_car.png", rename: 646 },
    { url: "https://docs.fivem.net/blips/radar_arena_rc_workshop.png", rename: 647 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_fire.png", rename: 648 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_flip.png", rename: 649 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_sea.png", rename: 650 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_turn.png", rename: 651 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_pit.png", rename: 652 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_mine.png", rename: 653 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_bomb.png", rename: 654 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_wall.png", rename: 655 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_brd.png", rename: 656 },
    { url: "https://docs.fivem.net/blips/radar_arena_trap_sbrd.png", rename: 657 },
    { url: "https://docs.fivem.net/blips/radar_arena_bruiser.png", rename: 658 },
    { url: "https://docs.fivem.net/blips/radar_arena_brutus.png", rename: 659 },
    { url: "https://docs.fivem.net/blips/radar_arena_cerberus.png", rename: 660 },
    { url: "https://docs.fivem.net/blips/radar_arena_deathbike.png", rename: 661 },
    { url: "https://docs.fivem.net/blips/radar_arena_dominator.png", rename: 662 },
    { url: "https://docs.fivem.net/blips/radar_arena_impaler.png", rename: 663 },
    { url: "https://docs.fivem.net/blips/radar_arena_imperator.png", rename: 664 },
    { url: "https://docs.fivem.net/blips/radar_arena_issi.png", rename: 665 },
    { url: "https://docs.fivem.net/blips/radar_arena_sasquatch.png", rename: 666 },
    { url: "https://docs.fivem.net/blips/radar_arena_scarab.png", rename: 667 },
    { url: "https://docs.fivem.net/blips/radar_arena_slamvan.png", rename: 668 },
    { url: "https://docs.fivem.net/blips/radar_arena_zr380.png", rename: 669 },
    { url: "https://docs.fivem.net/blips/radar_ap.png", rename: 670 },
    { url: "https://docs.fivem.net/blips/radar_comic_store.png", rename: 671 },
    { url: "https://docs.fivem.net/blips/radar_cop_car.png", rename: 672 },
    { url: "https://docs.fivem.net/blips/radar_rc_time_trials.png", rename: 673 },
    { url: "https://docs.fivem.net/blips/radar_king_of_the_hill.png", rename: 674 },
    { url: "https://docs.fivem.net/blips/radar_king_of_the_hill_teams.png", rename: 675 },
    { url: "https://docs.fivem.net/blips/radar_rucksack.png", rename: 676 },
    { url: "https://docs.fivem.net/blips/radar_shipping_container.png", rename: 677 },
    { url: "https://docs.fivem.net/blips/radar_agatha.png", rename: 678 },
    { url: "https://docs.fivem.net/blips/radar_casino.png", rename: 679 },
    { url: "https://docs.fivem.net/blips/radar_casino_table_games.png", rename: 680 },
    { url: "https://docs.fivem.net/blips/radar_casino_wheel.png", rename: 681 },
    { url: "https://docs.fivem.net/blips/radar_casino_concierge.png", rename: 682 },
    { url: "https://docs.fivem.net/blips/radar_casino_chips.png", rename: 683 },
    { url: "https://docs.fivem.net/blips/radar_casino_horse_racing.png", rename: 684 },
    { url: "https://docs.fivem.net/blips/radar_adversary_featured.png", rename: 685 },
    { url: "https://docs.fivem.net/blips/radar_roulette_1.png", rename: 686 },
    { url: "https://docs.fivem.net/blips/radar_roulette_2.png", rename: 687 },
    { url: "https://docs.fivem.net/blips/radar_roulette_3.png", rename: 688 },
    { url: "https://docs.fivem.net/blips/radar_roulette_4.png", rename: 689 },
    { url: "https://docs.fivem.net/blips/radar_roulette_5.png", rename: 690 },
    { url: "https://docs.fivem.net/blips/radar_roulette_6.png", rename: 691 },
    { url: "https://docs.fivem.net/blips/radar_roulette_7.png", rename: 692 },
    { url: "https://docs.fivem.net/blips/radar_roulette_8.png", rename: 693 },
    { url: "https://docs.fivem.net/blips/radar_roulette_9.png", rename: 694 },
    { url: "https://docs.fivem.net/blips/radar_roulette_10.png", rename: 695 },
    { url: "https://docs.fivem.net/blips/radar_roulette_11.png", rename: 696 },
    { url: "https://docs.fivem.net/blips/radar_roulette_12.png", rename: 697 },
    { url: "https://docs.fivem.net/blips/radar_roulette_13.png", rename: 698 },
    { url: "https://docs.fivem.net/blips/radar_roulette_14.png", rename: 699 },
    { url: "https://docs.fivem.net/blips/radar_roulette_15.png", rename: 700 },
    { url: "https://docs.fivem.net/blips/radar_roulette_16.png", rename: 701 },
    { url: "https://docs.fivem.net/blips/radar_roulette_17.png", rename: 702 },
    { url: "https://docs.fivem.net/blips/radar_roulette_18.png", rename: 703 },
    { url: "https://docs.fivem.net/blips/radar_roulette_19.png", rename: 704 },
    { url: "https://docs.fivem.net/blips/radar_roulette_20.png", rename: 705 },
    { url: "https://docs.fivem.net/blips/radar_roulette_21.png", rename: 706 },
    { url: "https://docs.fivem.net/blips/radar_roulette_22.png", rename: 707 },
    { url: "https://docs.fivem.net/blips/radar_roulette_23.png", rename: 708 },
    { url: "https://docs.fivem.net/blips/radar_roulette_24.png", rename: 709 },
    { url: "https://docs.fivem.net/blips/radar_roulette_25.png", rename: 710 },
    { url: "https://docs.fivem.net/blips/radar_roulette_26.png", rename: 711 },
    { url: "https://docs.fivem.net/blips/radar_roulette_27.png", rename: 712 },
    { url: "https://docs.fivem.net/blips/radar_roulette_28.png", rename: 713 },
    { url: "https://docs.fivem.net/blips/radar_roulette_29.png", rename: 714 },
    { url: "https://docs.fivem.net/blips/radar_roulette_30.png", rename: 715 },
    { url: "https://docs.fivem.net/blips/radar_roulette_31.png", rename: 716 },
    { url: "https://docs.fivem.net/blips/radar_roulette_32.png", rename: 717 },
    { url: "https://docs.fivem.net/blips/radar_roulette_33.png", rename: 718 },
    { url: "https://docs.fivem.net/blips/radar_roulette_34.png", rename: 719 },
    { url: "https://docs.fivem.net/blips/radar_roulette_35.png", rename: 720 },
    { url: "https://docs.fivem.net/blips/radar_roulette_36.png", rename: 721 },
    { url: "https://docs.fivem.net/blips/radar_roulette_0.png", rename: 722 },
    { url: "https://docs.fivem.net/blips/radar_roulette_00.png", rename: 723 },
    { url: "https://docs.fivem.net/blips/radar_limo.png", rename: 724 },
    { url: "https://docs.fivem.net/blips/radar_weapon_alien.png", rename: 725 },
    { url: "https://docs.fivem.net/blips/radar_race_open_wheel.png", rename: 726 },
    { url: "https://docs.fivem.net/blips/radar_rappel.png", rename: 727 },
    { url: "https://docs.fivem.net/blips/radar_swap_car.png", rename: 728 },
    { url: "https://docs.fivem.net/blips/radar_scuba_gear.png", rename: 729 },
    { url: "https://docs.fivem.net/blips/radar_cpanel_1.png", rename: 730 },
    { url: "https://docs.fivem.net/blips/radar_cpanel_2.png", rename: 731 },
    { url: "https://docs.fivem.net/blips/radar_cpanel_3.png", rename: 732 },
    { url: "https://docs.fivem.net/blips/radar_cpanel_4.png", rename: 733 },
    { url: "https://docs.fivem.net/blips/radar_snow_truck.png", rename: 734 },
    { url: "https://docs.fivem.net/blips/radar_buggy_1.png", rename: 735 },
    { url: "https://docs.fivem.net/blips/radar_buggy_2.png", rename: 736 },
    { url: "https://docs.fivem.net/blips/radar_zhaba.png", rename: 737 },
    { url: "https://docs.fivem.net/blips/radar_gerald.png", rename: 738 },
    { url: "https://docs.fivem.net/blips/radar_ron.png", rename: 739 },
    { url: "https://docs.fivem.net/blips/radar_arcade.png", rename: 740 },
    { url: "https://docs.fivem.net/blips/radar_drone_controls.png", rename: 741 },
    { url: "https://docs.fivem.net/blips/radar_rc_tank.png", rename: 742 },
    { url: "https://docs.fivem.net/blips/radar_stairs.png", rename: 743 },
    { url: "https://docs.fivem.net/blips/radar_camera_2.png", rename: 744 },
    { url: "https://docs.fivem.net/blips/radar_winky.png", rename: 745 },
    { url: "https://docs.fivem.net/blips/radar_mini_sub.png", rename: 746 },
    { url: "https://docs.fivem.net/blips/radar_kart_retro.png", rename: 747 },
    { url: "https://docs.fivem.net/blips/radar_kart_modern.png", rename: 748 },
    { url: "https://docs.fivem.net/blips/radar_military_quad.png", rename: 749 },
    { url: "https://docs.fivem.net/blips/radar_military_truck.png", rename: 750 },
    { url: "https://docs.fivem.net/blips/radar_ship_wheel.png", rename: 751 },
    { url: "https://docs.fivem.net/blips/radar_ufo.png", rename: 752 },
    { url: "https://docs.fivem.net/blips/radar_seasparrow2.png", rename: 753 },
    { url: "https://docs.fivem.net/blips/radar_dinghy2.png", rename: 754 },
    { url: "https://docs.fivem.net/blips/radar_patrol_boat.png", rename: 755 },
    { url: "https://docs.fivem.net/blips/radar_retro_sports_car.png", rename: 756 },
    { url: "https://docs.fivem.net/blips/radar_squadee.png", rename: 757 },
    { url: "https://docs.fivem.net/blips/radar_folding_wing_jet.png", rename: 758 },
    { url: "https://docs.fivem.net/blips/radar_valkyrie2.png", rename: 759 },
    { url: "https://docs.fivem.net/blips/radar_sub2.png", rename: 760 },
    { url: "https://docs.fivem.net/blips/radar_bolt_cutters.png", rename: 761 },
    { url: "https://docs.fivem.net/blips/radar_rappel_gear.png", rename: 762 },
    { url: "https://docs.fivem.net/blips/radar_keycard.png", rename: 763 },
    { url: "https://docs.fivem.net/blips/radar_password.png", rename: 764 },
    { url: "https://docs.fivem.net/blips/radar_island_heist_prep.png", rename: 765 },
    { url: "https://docs.fivem.net/blips/radar_island_party.png", rename: 766 },
    { url: "https://docs.fivem.net/blips/radar_control_tower.png", rename: 767 },
    { url: "https://docs.fivem.net/blips/radar_underwater_gate.png", rename: 768 },
    { url: "https://docs.fivem.net/blips/radar_power_switch.png", rename: 769 },
    { url: "https://docs.fivem.net/blips/radar_compound_gate.png", rename: 770 },
    { url: "https://docs.fivem.net/blips/radar_rappel_point.png", rename: 771 },
    { url: "https://docs.fivem.net/blips/radar_keypad.png", rename: 772 },
    { url: "https://docs.fivem.net/blips/radar_sub_controls.png", rename: 773 },
    { url: "https://docs.fivem.net/blips/radar_sub_periscope.png", rename: 774 },
    { url: "https://docs.fivem.net/blips/radar_sub_missile.png", rename: 775 },
    { url: "https://docs.fivem.net/blips/radar_painting.png", rename: 776 },
    { url: "https://docs.fivem.net/blips/radar_car_meet.png", rename: 777 },
    { url: "https://docs.fivem.net/blips/radar_car_test_area.png", rename: 778 },
    { url: "https://docs.fivem.net/blips/radar_auto_shop_property.png", rename: 779 },
    { url: "https://docs.fivem.net/blips/radar_docks_export.png", rename: 780 },
    { url: "https://docs.fivem.net/blips/radar_prize_car.png", rename: 781 },
    { url: "https://docs.fivem.net/blips/radar_test_car.png", rename: 782 },
    { url: "https://docs.fivem.net/blips/radar_car_robbery_board.png", rename: 783 },
    { url: "https://docs.fivem.net/blips/radar_car_robbery_prep.png", rename: 784 },
    { url: "https://docs.fivem.net/blips/radar_street_race_series.png", rename: 785 },
    { url: "https://docs.fivem.net/blips/radar_pursuit_series.png", rename: 786 },
    { url: "https://docs.fivem.net/blips/radar_car_meet_organiser.png", rename: 787 },
    { url: "https://docs.fivem.net/blips/radar_securoserv.png", rename: 788 },
    { url: "https://docs.fivem.net/blips/radar_bounty_collectibles.png", rename: 789 },
    { url: "https://docs.fivem.net/blips/radar_movie_collectibles.png", rename: 790 },
    { url: "https://docs.fivem.net/blips/radar_trailer_ramp.png", rename: 791 },
    { url: "https://docs.fivem.net/blips/radar_race_organiser.png", rename: 792 },
    { url: "https://docs.fivem.net/blips/radar_chalkboard_list.png", rename: 793 },
    { url: "https://docs.fivem.net/blips/radar_export_vehicle.png", rename: 794 },
    { url: "https://docs.fivem.net/blips/radar_train.png", rename: 795 },
    { url: "https://docs.fivem.net/blips/radar_heist_diamond.png", rename: 796 },
    { url: "https://docs.fivem.net/blips/radar_heist_doomsday.png", rename: 797 },
    { url: "https://docs.fivem.net/blips/radar_heist_island.png", rename: 798 },
    { url: "https://docs.fivem.net/blips/radar_slamvan2.png", rename: 799 },
    { url: "https://docs.fivem.net/blips/radar_crusader.png", rename: 800 },
    { url: "https://docs.fivem.net/blips/radar_construction_outfit.png", rename: 801 },
    { url: "https://docs.fivem.net/blips/radar_overlay_jammed.png", rename: 802 },
    { url: "https://docs.fivem.net/blips/radar_heist_island_unavailable.png", rename: 803 },
    { url: "https://docs.fivem.net/blips/radar_heist_diamond_unavailable.png", rename: 804 },
    { url: "https://docs.fivem.net/blips/radar_heist_doomsday_unavailable.png", rename: 805 },
    { url: "https://docs.fivem.net/blips/radar_placeholder_7.png", rename: 806 },
    { url: "https://docs.fivem.net/blips/radar_placeholder_8.png", rename: 807 },
    { url: "https://docs.fivem.net/blips/radar_placeholder_9.png", rename: 808 },
    { url: "https://docs.fivem.net/blips/radar_featured_series.png", rename: 809 },
    { url: "https://docs.fivem.net/blips/radar_vehicle_for_sale.png", rename: 810 },
    { url: "https://docs.fivem.net/blips/radar_van_keys.png", rename: 811 },
    { url: "https://docs.fivem.net/blips/radar_suv_service.png", rename: 812 },
    { url: "https://docs.fivem.net/blips/radar_security_contract.png", rename: 813 },
    { url: "https://docs.fivem.net/blips/radar_safe.png", rename: 814 },
    { url: "https://docs.fivem.net/blips/radar_ped_r.png", rename: 815 },
    { url: "https://docs.fivem.net/blips/radar_ped_e.png", rename: 816 },
    { url: "https://docs.fivem.net/blips/radar_payphone.png", rename: 817 },
    { url: "https://docs.fivem.net/blips/radar_patriot3.png", rename: 818 },
    { url: "https://docs.fivem.net/blips/radar_music_studio.png", rename: 819 },
    { url: "https://docs.fivem.net/blips/radar_jubilee.png", rename: 820 },
    { url: "https://docs.fivem.net/blips/radar_granger2.png", rename: 821 },
    { url: "https://docs.fivem.net/blips/radar_explosive_charge.png", rename: 822 },
    { url: "https://docs.fivem.net/blips/radar_deity.png", rename: 823 },
    { url: "https://docs.fivem.net/blips/radar_d_champion.png", rename: 824 },
    { url: "https://docs.fivem.net/blips/radar_buffalo4.png", rename: 825 },
    { url: "https://docs.fivem.net/blips/radar_agency.png", rename: 826 },
    { url: "https://docs.fivem.net/blips/radar_biker_bar.png", rename: 827 },
    { url: "https://docs.fivem.net/blips/radar_simeon_overlay.png", rename: 828 },
    { url: "https://docs.fivem.net/blips/radar_junk_skydive.png", rename: 829 },
    { url: "https://docs.fivem.net/blips/radar_luxury_car_showroom.png", rename: 830 },
    { url: "https://docs.fivem.net/blips/radar_car_showroom.png", rename: 831 },
    { url: "https://docs.fivem.net/blips/radar_car_showroom_simeon.png", rename: 832 },
    { url: "https://docs.fivem.net/blips/radar_flaming_skull.png", rename: 833 },
    { url: "https://docs.fivem.net/blips/radar_weapon_ammo.png", rename: 834 },
    { url: "https://docs.fivem.net/blips/radar_community_series.png", rename: 835 },
    { url: "https://docs.fivem.net/blips/radar_cayo_series.png", rename: 836 },
    { url: "https://docs.fivem.net/blips/radar_clubhouse_contract.png", rename: 837 },
    { url: "https://docs.fivem.net/blips/radar_agent_ulp.png", rename: 838 },
    { url: "https://docs.fivem.net/blips/radar_acid.png", rename: 839 },
    { url: "https://docs.fivem.net/blips/radar_acid_lab.png", rename: 840 },
    { url: "https://docs.fivem.net/blips/radar_dax_overlay.png", rename: 841 },
    { url: "https://docs.fivem.net/blips/radar_dead_drop_package.png", rename: 842 },
    { url: "https://docs.fivem.net/blips/radar_downtown_cab.png", rename: 843 },
    { url: "https://docs.fivem.net/blips/radar_gun_van.png", rename: 844 },
    { url: "https://docs.fivem.net/blips/radar_stash_house.png", rename: 845 },
    { url: "https://docs.fivem.net/blips/radar_tractor.png", rename: 846 },
    { url: "https://docs.fivem.net/blips/radar_warehouse_juggalo.png", rename: 847 },
    { url: "https://docs.fivem.net/blips/radar_warehouse_juggalo_dax.png", rename: 848 },
    { url: "https://docs.fivem.net/blips/radar_weapon_crowbar.png", rename: 849 },
    { url: "https://docs.fivem.net/blips/radar_duffel_bag.png", rename: 850 },
    { url: "https://docs.fivem.net/blips/radar_oil_tanker.png", rename: 851 },
    { url: "https://docs.fivem.net/blips/radar_acid_lab_tent.png", rename: 852 },
    { url: "https://docs.fivem.net/blips/radar_van_burrito.png", rename: 853 },
    { url: "https://docs.fivem.net/blips/radar_acid_boost.png", rename: 854 },
    { url: "https://docs.fivem.net/blips/radar_ped_gang_leader.png", rename: 855 },
    { url: "https://docs.fivem.net/blips/radar_multistorey_garage.png", rename: 856 },
    { url: "https://docs.fivem.net/blips/radar_seized_asset_sales.png", rename: 857 },
    { url: "https://docs.fivem.net/blips/radar_cayo_attrition.png", rename: 858 },
    { url: "https://docs.fivem.net/blips/radar_bicycle.png", rename: 859 },
    { url: "https://docs.fivem.net/blips/radar_bicycle_trial.png", rename: 860 },
    { url: "https://docs.fivem.net/blips/radar_raiju.png", rename: 861 },
    { url: "https://docs.fivem.net/blips/radar_conada2.png", rename: 862 },
    { url: "https://docs.fivem.net/blips/radar_overlay_ready_for_sell.png", rename: 863 },
    { url: "https://docs.fivem.net/blips/radar_overlay_missing_supplies.png", rename: 864 },
    { url: "https://docs.fivem.net/blips/radar_streamer216.png", rename: 865 },
    { url: "https://docs.fivem.net/blips/radar_signal_jammer.png", rename: 866 },
    { url: "https://docs.fivem.net/blips/radar_salvage_yard.png", rename: 867 },
    { url: "https://docs.fivem.net/blips/radar_robbery_prep_equipment.png", rename: 868 },
    { url: "https://docs.fivem.net/blips/radar_robbery_prep_overlay.png", rename: 869 },
    { url: "https://docs.fivem.net/blips/radar_yusuf.png", rename: 870 },
    { url: "https://docs.fivem.net/blips/radar_vincent.png", rename: 871 },
    { url: "https://docs.fivem.net/blips/radar_vinewood_garage.png", rename: 872 },
    { url: "https://docs.fivem.net/blips/radar_lstb.png", rename: 873 },
    { url: "https://docs.fivem.net/blips/radar_cctv_workstation.png", rename: 874 },
    { url: "https://docs.fivem.net/blips/radar_hacking_device.png", rename: 875 },
    { url: "https://docs.fivem.net/blips/radar_race_drag.png", rename: 876 },
    { url: "https://docs.fivem.net/blips/radar_race_drift.png", rename: 877 },
    { url: "https://docs.fivem.net/blips/radar_casino_prep.png", rename: 878 },
    { url: "https://docs.fivem.net/blips/radar_planning_wall.png", rename: 879 },
    { url: "https://docs.fivem.net/blips/radar_weapon_crate.png", rename: 880 },
    { url: "https://docs.fivem.net/blips/radar_weapon_snowball.png", rename: 881 },
    { url: "https://docs.fivem.net/blips/radar_train_signals_green.png", rename: 882 },
    { url: "https://docs.fivem.net/blips/radar_train_signals_red.png", rename: 883 },
    { url: "https://docs.fivem.net/blips/radar_office_transporter.png", rename: 884 },
    { url: "https://docs.fivem.net/blips/radar_yankton_survival.png", rename: 885 },
    { url: "https://docs.fivem.net/blips/radar_daily_bounty.png", rename: 886 },
    { url: "https://docs.fivem.net/blips/radar_bounty_target.png", rename: 887 },
    { url: "https://docs.fivem.net/blips/radar_filming_schedule.png", rename: 888 },
    { url: "https://docs.fivem.net/blips/radar_pizza_this.png", rename: 889 },
    { url: "https://docs.fivem.net/blips/radar_aircraft_carrier.png", rename: 890 },
    { url: "https://docs.fivem.net/blips/radar_weapon_emp.png", rename: 891 },
    { url: "https://docs.fivem.net/blips/radar_maude_eccles.png", rename: 892 },
    { url: "https://docs.fivem.net/blips/radar_bail_bonds_office.png", rename: 893 },
    { url: "https://docs.fivem.net/blips/radar_weapon_emp_mine.png", rename: 894 },
    { url: "https://docs.fivem.net/blips/radar_zombie_disease.png", rename: 895 },
    { url: "https://docs.fivem.net/blips/radar_zombie_proximity.png", rename: 896 },
    { url: "https://docs.fivem.net/blips/radar_zombie_fire.png", rename: 897 },
    { url: "https://docs.fivem.net/blips/radar_animal_possessed.png", rename: 898 },
    { url: "https://docs.fivem.net/blips/radar_mobile_phone.png", rename: 899 },
    { url: "https://docs.fivem.net/blips/radar_garment_factory.png", rename: 900 },
    { url: "https://docs.fivem.net/blips/radar_garment_factory_for_sale.png", rename: 901 },
    { url: "https://docs.fivem.net/blips/radar_garment_factory_equipment.png", rename: 902 },
    { url: "https://docs.fivem.net/blips/radar_field_hangar.png", rename: 903 },
    { url: "https://docs.fivem.net/blips/radar_field_hangar_for_sale.png", rename: 904 },
    { url: "https://docs.fivem.net/blips/radar_cargobob_ch53.png", rename: 905 },
    { url: "https://docs.fivem.net/blips/radar_chopper_lift_ammo.png", rename: 906 },
    { url: "https://docs.fivem.net/blips/radar_chopper_lift_armor.png", rename: 907 },
    { url: "https://docs.fivem.net/blips/radar_chopper_lift_explosives.png", rename: 908 },
    { url: "https://docs.fivem.net/blips/radar_chopper_lift_upgrade.png", rename: 909 },
    { url: "https://docs.fivem.net/blips/radar_chopper_lift_weapon.png", rename: 910 },
    { url: "https://docs.fivem.net/blips/radar_cargo_ship.png", rename: 911 },
    { url: "https://docs.fivem.net/blips/radar_submarine_missile.png", rename: 912 },
    { url: "https://docs.fivem.net/blips/radar_propeller_engine.png", rename: 913 },
    { url: "https://docs.fivem.net/blips/radar_shark.png", rename: 914 },
    { url: "https://docs.fivem.net/blips/radar_fast_travel.png", rename: 915 },
    { url: "https://docs.fivem.net/blips/radar_plane_duster2.png", rename: 916 },
    { url: "https://docs.fivem.net/blips/radar_plane_titan2.png", rename: 917 },
    { url: "https://docs.fivem.net/blips/radar_collectible.png", rename: 918 },
    { url: "https://docs.fivem.net/blips/radar_field_hangar_discount.png", rename: 919 },
];

export const colors = [
    { color: '#fefefe', id: 0, label: 'White' },
    { color: '#e03232', id: 1, label: 'Red' },
    { color: '#71cb71', id: 2, label: 'Green' },
    { color: '#e03232', id: 2, label: 'Red' },
    { color: '#5db6e5', id: 2, label: 'Blue' },
    { color: '#5db6e5', id: 3, label: 'Blue' },
    { color: '#e03232', id: 3, label: 'Red' },
    { color: '#fefefe', id: 4, label: 'White' },
    { color: '#e03232', id: 4, label: 'Red' },
    { color: '#5db6e5', id: 4, label: 'Blue' },
    { color: '#eec64e', id: 5, label: 'Yellow' },
    { color: '#e03232', id: 5, label: 'Red' },
    { color: '#5db6e5', id: 5, label: 'Blue' },
    { color: '#c25050', id: 6, label: 'Light Red' },
    { color: '#9c6eaf', id: 7, label: 'Violet' },
    { color: '#fe7ac3', id: 8, label: 'Pink' },
    { color: '#f59d79', id: 9, label: 'Light Orange' },
    { color: '#b18f83', id: 10, label: 'Light Brown' },
    { color: '#8dcea7', id: 11, label: 'Light Green' },
    { color: '#70a8ae', id: 12, label: 'Light Blue' },
    { color: '#d3d1e7', id: 13, label: 'Light Purple' },
    { color: '#8f7e98', id: 14, label: 'Dark Purple' },
    { color: '#6ac4bf', id: 15, label: 'Cyan' },
    { color: '#d5c398', id: 16, label: 'Light Yellow' },
    { color: '#ea8e50', id: 17, label: 'Orange' },
    { color: '#97cae9', id: 18, label: 'Light Blue' },
    { color: '#b26287', id: 19, label: 'Dark Pink' },
    { color: '#8f8d79', id: 20, label: 'Dark Yellow' },
    { color: '#a6755e', id: 21, label: 'Dark Orange' },
    { color: '#afa8a8', id: 22, label: 'Light Gray' },
    { color: '#e78d9a', id: 23, label: 'Light Pink' },
    { color: '#bbd65b', id: 24, label: 'Lemon Green' },
    { color: '#0c7b56', id: 25, label: 'Forest Green' },
    { color: '#7ac3fe', id: 26, label: 'Electric Blue' },
    { color: '#ab3ce6', id: 27, label: 'Bright Purple' },
    { color: '#cda80c', id: 28, label: 'Dark Yellow' },
    { color: '#4561ab', id: 29, label: 'Dark Blue' },
    { color: '#29a5b8', id: 30, label: 'Dark Cyan' },
    { color: '#b89b7b', id: 31, label: 'Light Brown' },
    { color: '#c8e0fe', id: 32, label: 'Light Blue' },
    { color: '#f0f096', id: 33, label: 'Light Yellow' },
    { color: '#ed8ca1', id: 34, label: 'Light Pink' },
    { color: '#f98a8a', id: 35, label: 'Light Red' },
    { color: '#fbeea5', id: 36, label: 'Beige' },
    { color: '#fefefe', id: 37, label: 'White' },
    { color: '#2c6db8', id: 38, label: 'Blue' },
    { color: '#9a9a9a', id: 39, label: 'Light Gray' },
    { color: '#4c4c4c', id: 40, label: 'Dark Gray' },
    { color: '#F29D9D', id: 41, label: 'Pink Red' },
    { color: '#6CB7D6', id: 42, label: 'Blue' },
    { color: '#AFEDAE', id: 43, label: 'Light Green' },
    { color: '#FFA75F', id: 44, label: 'Light Orange' },
    { color: '#F1F1F1', id: 45, label: 'White' },
    { color: '#ECF029', id: 46, label: 'Gold' },
    { color: '#FF9A18', id: 47, label: 'Orange' },
    { color: '#F644A5', id: 48, label: 'Brilliant Rose' },
    { color: '#E03A3A', id: 49, label: 'Red' },
    { color: '#5db6e5', id: 49, label: 'Blue' },
    { color: '#8A6DE3', id: 50, label: 'Medium Purple' },
    { color: '#FF8B5C', id: 51, label: 'Salmon' },
    { color: '#416C41', id: 52, label: 'Dark Green' },
    { color: '#B3DDF3', id: 53, label: 'Blizzard Blue' },
    { color: '#3A6479', id: 54, label: 'Oracle Blue' },
    { color: '#A0A0A0', id: 55, label: 'Silver' },
    { color: '#847232', id: 56, label: 'Brown' },
    { color: '#65B9E7', id: 57, label: 'Blue' },
    { color: '#4B4175', id: 58, label: 'East Bay' },
    { color: '#E13B3B', id: 59, label: 'Red' },
    { color: '#F0CB58', id: 60, label: 'Yellow Orange' },
    { color: '#CD3F98', id: 61, label: 'Mulberry Pink' },
    { color: '#CFCFCF', id: 62, label: 'Alto Gray' },
    { color: '#276A9F', id: 63, label: 'Jelly Bean Blue' },
    { color: '#D87B1B', id: 64, label: 'Dark Orange' },
    { color: '#8E8393', id: 65, label: 'Mamba' },
    { color: '#F0CB57', id: 66, label: 'Yellow Orange' },
    { color: '#e03232', id: 66, label: 'Red' },
    { color: '#5db6e5', id: 66, label: 'Blue' },
    { color: '#65B9E7', id: 67, label: 'Blue' },
    { color: '#e03232', id: 67, label: 'Red' },
    { color: '#65B9E7', id: 68, label: 'Blue' },
    { color: '#e03232', id: 68, label: 'Red' },
    { color: '#79CD79', id: 69, label: 'Green' },
    { color: '#e03232', id: 69, label: 'Red' },
    { color: '#5db6e5', id: 69, label: 'Blue' },
    { color: '#EFCA57', id: 70, label: 'Yellow Orange' },
    { color: '#EFCA57', id: 71, label: 'Yellow Orange' },
    { color: '#3D3D3D', id: 72, label: 'Transparent Black' },
    { color: '#EFCA57', id: 73, label: 'Yellow Orange' },
    { color: '#65B9E7', id: 74, label: 'Blue' },
    { color: '#e03232', id: 75, label: 'Red' },
    { color: '#782323', id: 76, label: 'Deep red' },
    { color: '#65B9E7', id: 77, label: 'Blue' },
    { color: '#3A6479', id: 78, label: 'Oracle Blue' },
    { color: '#e03232', id: 79, label: 'Transparent Red' },
    { color: '#65B9E7', id: 80, label: 'Transparent Blue' },
    { color: '#F2A40C', id: 81, label: 'Orange' },
    { color: '#A4CCAA', id: 82, label: 'Light Green' },
    { color: '#A854F2', id: 83, label: 'Purple' },
    { color: '#65B9E7', id: 84, label: 'Blue' },
    { color: '#3D3D3D', id: 85, label: 'Transparent Black' }
];